name: 🚥 Codespell

# Workflow to check spelling errors on the changed files within the current pull request.
#
# The previous version already did a complete check on the whole repository, therefore,
# we prefer only to check the added/changed files for spelling errors.

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🔸 Get Changed Files from Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # get file names and separate them with space ' '
          files=$(gh pr diff ${{ github.event.pull_request.number }} --name-only | xargs -I {} sh -c 'echo "./{}"' | tr '\n' ' ')
          echo "CHANGED_FILES=$files" >> "$GITHUB_ENV"          

      - name: 🔸 Output Changed Files
        run: echo ${{ env.CHANGED_FILES }}
          
      - name: 🔸 Check for Spelling Errors for Changed Files
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
          skip: nothing
          path: ${{ env.CHANGED_FILES }}

